language: python

install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libxslt-dev zlib1g-dev
  - pip install stix==1.2.0.1
  - pip install stix-validator

script: ./test_idioms.sh

branches:
  only:
    - master

notifications:
  email:
    - stix-commits-list@lists.mitre.org

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fbfa85a0bb8108ad060
    on_success: change
    on_failure: always
    on_start: false

