name: STIX Docs
markdown: kramdown
highlighter: rouge
redirects: yes

copyright: The MITRE Corporation
contact_email: stix@mitre.org
generate_documentation: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', "Rakefile", "LICENSE"]

current_version: 1.2

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-redirect-from

encoding: utf-8
