name: STIX Docs
markdown: redcarpet
highlighter: pygments
redirects: yes

copyright: The MITRE Corporation
contact_email: stix@mitre.org
generate_documentation: true

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', "Rakefile", "LICENSE", "documentation", "data-model"]

current_version: 1.2

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

gems:
  - jekyll-redirect-from

encoding: utf-8
